//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Donneur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donneur()
        {
            this.Transplantation = new HashSet<Transplantation>();
        }
    
        public int Code_Do { get; set; }
        [DisplayName("Vivant")]
        public Nullable<bool> Vivant_Do { get; set; }
        [DisplayName("ADN")]
        public string ADN_Do { get; set; }
        [DisplayName("Allergies")]
        public string Allergie_Do { get; set; }
        [DisplayName("Raison du décès")]
        public string Raison_Deces_Do { get; set; }
        public string Virus { get; set; }
        [DisplayName("Group sanguin")]
        public string Groupe_Sanguin_Do { get; set; }
        [DisplayName("Date du transplant")]
        public Nullable<System.DateTime> Date_Transplant_Do { get; set; }
        public int Code_Patient { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transplantation> Transplantation { get; set; }
    }
}
