//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGroupe2Entities : DbContext
    {
        public DBGroupe2Entities()
            : base("name=DBGroupe2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Donneur> Donneur { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Role_User> Role_User { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tests> Tests { get; set; }
        public virtual DbSet<Tests_Patient> Tests_Patient { get; set; }
        public virtual DbSet<Transplantation> Transplantation { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
