//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Donneur = new HashSet<Donneur>();
            this.Tests_Patient = new HashSet<Tests_Patient>();
            this.Transplantation = new HashSet<Transplantation>();
        }
        [DisplayName("Numéro du dossier")]
        public int Code_Patient { get; set; }
        [DisplayName("Nom du patient")]
        public string Nom_Patient { get; set; }
        [DisplayName("Prénom du patient")]
        public string Prenom_Patient { get; set; }
        [DisplayName("Numéro d'assurance maladies")]
        public string NAS_Patient { get; set; }
        [DisplayName("Date de naissance")]
        public Nullable<System.DateTime> DateNaissance_Patient { get; set; }
        [DisplayName("Allergies")]
        public string Allergie_Patient { get; set; }
        [DisplayName("Maladie original du patient")]
        public string Maladie_Original_Patient { get; set; }
        [DisplayName("Date de la transplantation")]
        public Nullable<System.DateTime> Date_Transplant_Patient { get; set; }
        [DisplayName("Côté de la transplantation")]
        public string Coter_Transplant_Patient { get; set; }

        [DisplayName("ABV")]
        public Nullable<int> ABV_Patient { get; set; }

        [DisplayName("Energy")]
        public string Anergy_Patient { get; set; }

        [DisplayName("PPD_Patient")]
        public Nullable<bool> PPD_Patient { get; set; }

        [DisplayName("HbsAg_Patient")]
        public Nullable<bool> HbsAg_Patient { get; set; }

        [DisplayName("CMV_Patient")]
        public Nullable<bool> CMV_Patient { get; set; }

        [DisplayName("Transfusion_Patient")]
        public string Transfusion_Patient { get; set; }

        [DisplayName("VV_ByPass_Patient")]
        public Nullable<bool> VV_ByPass_Patient { get; set; }

        [DisplayName("Antifib_Lytics_Patient")]
        public Nullable<bool> Antifib_Lytics_Patient { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donneur> Donneur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tests_Patient> Tests_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transplantation> Transplantation { get; set; }
    }
}
