//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Tests_Patient
    {
        public int Code_Patient_TP { get; set; }
        public int Code_Test_TP { get; set; }
        [DisplayName("Résultat")]
        public string Resultat { get; set; }
        [DisplayName("Date du teste")]
        public Nullable<System.DateTime> Date_test { get; set; }
        public int Code_Patient { get; set; }
        public int Code_Test { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
